version: "3.6"
services:
  db:
    image: mysql/mysql-server
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: words_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      - webnet
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8888:8888"
    networks:
      - webnet
networks:
  webnet:
